<?xml version="1.0" encoding="UTF-8"?>

<!-- xml内引入dtd -->
<!DOCTYPE CATALOG [		

<!-- 引用实体 xml中使用 -->
<!ENTITY AUTHOR "John Doe">
<!ENTITY COMPANY "JD Power Tools, Inc.">
<!ENTITY EMAIL "jd@jd-tools.com">

<!-- 元素定义 -->
<!ELEMENT CATALOG (PRODUCT+)>

<!ELEMENT PRODUCT			
(SPECIFICATIONS+,OPTIONS?,PRICE+,NOTES?)>

<!-- 属性定义 -->
<!ATTLIST PRODUCT
NAME CDATA #IMPLIED
CATEGORY (HandTool|Table|Shop-Professional) "HandTool"
PARTNUM CDATA #IMPLIED
PLANT (Pittsburgh|Milwaukee|Chicago) "Chicago"
INVENTORY (InStock|Backordered|Discontinued) "InStock">

<!ELEMENT SPECIFICATIONS (#PCDATA)>
<!ATTLIST SPECIFICATIONS
WEIGHT CDATA #IMPLIED
POWER CDATA #IMPLIED>

<!ELEMENT OPTIONS (#PCDATA)>
<!ATTLIST OPTIONS
FINISH (Metal|Polished|Matte) "Matte" 
ADAPTER (Included|Optional|NotApplicable) "Included"
CASE (HardShell|Soft|NotApplicable) "HardShell">

<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST PRICE
MSRP CDATA #IMPLIED
WHOLESALE CDATA #IMPLIED
STREET CDATA #IMPLIED
SHIPPING CDATA #IMPLIED>

<!ELEMENT NOTES (#PCDATA)>

]>
<CATALOG>
	<PRODUCT NAME="first" CATEGORY="HandTool" PARTNUM="a"
		PLANT="Pittsburgh">
		<SPECIFICATIONS>specifications</SPECIFICATIONS>
		<OPTIONS>option</OPTIONS>
		<PRICE>$10</PRICE>
		<NOTES>notes</NOTES>
	</PRODUCT>
</CATALOG>